- name: Install postgresql@15 using homebrew
  community.general.homebrew:
    update_homebrew: yes
    name: postgresql@15
    state: present
- name: Start postgresl
  command: brew services start postgresql@15
- name: Check for default database
  command: "psql {{ ansible_user_id }} -c '\\q'"
  register: default_database
  ignore_errors: yes
- name: Create user's default database
  command: "createdb {{ ansible_user_id }}"
  when: default_database.failed == True
