- name: Install postgresql@15 using homebrew
  community.general.homebrew:
    update_homebrew: true
    name: postgresql@15
    state: present
- name: Add postgres directory to the PATH
  blockinfile:
    marker: "### {mark} INITIALIZE postgresql@15"
    mode: 0644
    path: "{{ item }}"
    create: true
    block: |
      export PATH="$HOMEBREW_PREFIX/opt/postgresql@15/bin:$PATH"
    state: present
  with_items:
    - "~/.zshrc"
# - name: Source updated .zshrc
#   become: true
#   become_user: "{{ ansible_user_id }}"
#   shell: source ~/.zshrc
#   args:
#     executable: /bin/zsh
- name: Start postgresl
  command: $HOMEBREW_PREFIX/bin/brew services start postgresql@15
- name: Check for default database
  command: "$HOMEBREW_PREFIX/opt/postgresql@15/bin/psql -c '\\q'"
  register: default_database
  ignore_errors: true
- name: Create user's default database
  command: "$HOMEBREW_PREFIX/opt/postgresql@15/bin/createdb {{ ansible_user_id }}"
  when: default_database.failed == True
