- name: Install postgresql@15 using homebrew
  community.general.homebrew:
    update_homebrew: yes
    name: postgresql@15
    state: present
# - name: Add PATH for postgresql@15
#   command: echo 'export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"' >> ~/.zshrc && source ~/.zshrc
- name: Add postgres directory to the PATH
  lineinfile:
    marker: "### {mark} Add postgresql@15 directory to the PATH"
    dest: ~/.zshrc
    line: export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
- name: Start postgresl
  command: brew services start postgresql@15
- name: Check for default database
  command: "psql {{ ansible_user_id }} -c '\\q'"
  register: default_database
  ignore_errors: yes
- name: Create user's default database
  command: "createdb {{ ansible_user_id }}"
  when: default_database.failed == True
