---
- name: install
  hosts: localhost
  gather_facts: true
  vars:
    asdf_user: "{{ ansible_user_id }}"
    wanted_node_version: "18"
  connection: local
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

  roles:
    - misc-utils
    - nodejs
    - ssh-key
    - aliases
    - zsh
    - postgresql

