---
- name: install
  hosts: 127.0.0.1
  gather_facts: yes
  vars_files:
    - variables.yml
  connection: local
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
