- name: 
  amazon.aws.ec2_vpc_net_info:
    region: "us-east-1"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
- name: Create ec2 key
  ec2_key:
        name: "key"
        region: "us-east-1"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
  register: ec2_key
- name: Save the key in a file
  copy: 
        content: "{{ ec2_key.key.private_key }}"  
        dest: "~/.ssh/ec2_key.pem"  
        mode: 0400
  when: ec2_key.changed
- name: "Allocate Instances"
  include_tasks: 
    file: allocate-instance.yml
    apply: 
      vars:
        - student_name: '{{ item }}'
        - cohort: '2109-LSU-RM-WEB-FT'
  with_items: 
    - Bart Dorsey
- name: "Refresh Inventory"
  meta: refresh_inventory