- name: apt upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
- name: apt install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name: 
      - zsh
      - acl
      - git
      - python3-pip
      - zip
      - unzip
      - grc
      - pgcli
      - htop
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
