- name: Configure GIT username
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{git_user}}"
- name: Configure GIT email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{git_email}}"
- name: Configure GIT Pull to use Rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: "true"
