- name: Determine installed brews
  command: 'brew list'
  register: brews
  changed_when: false
- name: Install various useful homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - insomnia
    - visual-studio-code
    - postico
    - postbird
  when: 
    - item not in brews.stdout_lines
  ignore_errors: yes
- name: Install various useful homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - zip
    - grc
    - pgcli
    - htop
    - font-fira-code-nerd-font    
  when: 
    - item not in brews.stdout_lines
- name: Install code symlink for Visual Studio Code
  file:
    src: "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
    dest: "/usr/local/bin/code"
    state: link
