- name: Create ~/.local/bin
  file: 
    path: ~/.local/bin
    state: directory
- name: Add common directories to the PATH
  blockinfile: 
    marker: "### {mark} Add common directories to the PATH"
    path: ~/.zshrc
    block: |
      export PATH=$HOME/.local/bin:$PATH