- name: Install postgresql using homebrew
  community.general.homebrew:
    update_homebrew: yes
    name: postgres
    state: present
- name: Start postgresl
  command: /usr/local/bin/brew services start postgresql
- name: Create user's default database
  community.postgresql.postgresql_db:
    name: "{{ ansible_user_id }}"
