- name: APT install PostgreSQL
  become: yes
  apt:
    update_cache: yes
    state: present
    name: 
      - postgresql
      - python3-psycopg2
      - python-psycopg2
- name: Start postgresql
  become: yes
  become_user: root
  ansible.builtin.service:
    name: postgresql
    state: started
- name: Get Postgres Version
  become: yes
  become_user: postgres
  community.postgresql.postgresql_info:
    filter: version
  register: postgres_version
- name: Allow trusted local connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.version.major}}/main/pg_hba.conf
    contype: local
    method: trust
- name: Allow trusted host connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.version.major}}/main/pg_hba.conf
    contype: host
    method: trust
- name: Start postgresql
  become: yes
  become_user: root
  ansible.builtin.service:
    name: postgresql
    state: started
- name: Create postgres user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ the_user }}"
    role_attr_flags: SUPERUSER
- name: Create user's default database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ the_user }}"
