- name: change user shell to zsh
  become: yes
  user:
    name: "{{ the_user }}"
    shell: /bin/zsh
- name: Install starship prompt
  become: yes
  shell: 
    cmd: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
    creates: /usr/local/bin/starship
- name: Add starship to zshrc
  blockinfile:
    marker: "### {mark} Initialized Starship Prompt"
    mode: 0644
    path: ~/.zshrc
    create: yes
    block: eval "$(starship init zsh)"
- name: Set EDITOR Environment variable
  blockinfile: 
    marker: "### {mark} SET VSCODE TO BE THE DEFAULT EDITOR"
    dest: ~/.{{ item }}
    block: |
      export EDITOR="code -w"
  with_items:
    - zshrc
