- name: change user shell to zsh
  become: yes
  user:
    name: "{{ the_user }}"
    shell: /bin/zsh
- name: Install starship prompt
  become: yes
  shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
- name: Add starship to bashrc
  blockinfile:
    marker: "### {mark} Initialized Starship Prompt"
    mode: 0644
    path: ~/.bashrc
    create: yes
    block: eval "$(starship init bash)"
- name: Add starship to zshrc
  blockinfile:
    marker: "### {mark} Initialized Starship Prompt"
    mode: 0644
    path: ~/.zshrc
    create: yes
    block: eval "$(starship init zsh)"
- name: Set EDITOR Environment variable
  blockinfile: 
    marker: "### {mark} SET VSCODE TO BE THE DEFAULT EDITOR"
    dest: ~/.{{ item }}
    block: |
      export EDITOR="code -w"
  with_items:
    - bashrc
    - zshrc
- name: Setup Common useful aliases
  blockinfile:
    marker: "### {mark} Common Useful Shell Aliases"
    dest: ~/.{{ item }}
    block: |
      alias open='explorer.exe'
      alias wsl='wsl.exe'
  with_items:
    - bashrc
    - zshrc
