- name: apt upgrade
  become: true
  apt:
    update_cache: yes
    upgrade: full
- name: apt install dependencies
  become: true
  apt:
    update_cache: yes
    state: present
    name:
      - zsh
      - acl
      - git
      - python3-pip
      - zip
      - unzip
      - grc
      - pgcli
      - htop
      - curl
