- name: apt upgrade
  become: true
  apt:
    update_cache: yes
    upgrade: full
- name: apt install dependencies
  become: true
  apt:
    update_cache: yes
    state: present
    name:
      - zsh
      - acl
      - git
      - python3-pip
      - zip
      - unzip
      - grc
      - pgcli
      - htop
      - curl
- name: apt install GH CLI if Ubuntu >= 22
  become: true
  apt:
    update_cache: true
    state: present
    name:
      - gh
  when: ansible_facts.distribution_major_version | int >= 22
